spring:
  application:
    name: activity-service
  data:
    mongodb:
      uri: mongodb+srv://root:qu0M7TNa9tflMAwM@cluster0.qkkvbxu.mongodb.net/fitness-activity?retryWrites=true&w=majority&appName=Cluster0
      database: fitness-activity
  jackson: # this is used to not include null values in JSON responses
    default-property-inclusion: non_null
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


kafka:
  topic:
    name: activity-events

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


server:
  port: 8082