spring:
  application:
    name: ai-service
  data:
    mongodb:
      uri: mongodb+srv://root:qu0M7TNa9tflMAwM@cluster0.qkkvbxu.mongodb.net/ai-recommendation-fitness?retryWrites=true&w=majority&appName=Cluster0
      database: ai-recommendation-fitness
  jackson: # this is used to not include null values in JSON responses
    default-property-inclusion: non_null

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8083
